CREATE ROLE keycloak WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:piGqaGEGjTiqI7E2dpqZLg==$pLAbOXqozlDXBR8yGQ49fzT3WTLGK7eLFfZRBa11DwM=:qx+R6IKJYUID/fbRM5aIcDmUBfKx+dnXKdtCYa/KP0Q=';

CREATE ROLE api WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:rKUhNLlW31B0S1GHBZB0Zg==$/ru75zsASDV5tcyl75ihsaN6nuQe79p9ax9qZJwOdpc=:Udpg9zcN0hnmjIizxzsOCEQKA/XWHamPr3Kp8KTpiJc=';

CREATE DATABASE api
    WITH
    OWNER = api
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

GRANT TEMPORARY, CONNECT ON DATABASE api TO PUBLIC;

GRANT ALL ON DATABASE api TO api;

CREATE DATABASE api_test
    WITH
    OWNER = api
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

GRANT TEMPORARY, CONNECT ON DATABASE api_test TO PUBLIC;

GRANT ALL ON DATABASE api_test TO api;

CREATE DATABASE keycloak
    WITH
    OWNER = keycloak
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

GRANT TEMPORARY, CONNECT ON DATABASE keycloak TO PUBLIC;

GRANT ALL ON DATABASE keycloak TO keycloak;