spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/api
    username: api
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers:
        - localhost:9092
      group-id: cnabparser-api
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    admin:
      auto-create: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/desafio
          jwk-set-uri: http://localhost:8080/realms/desafio/protocol/openid-connect/certs
server:
  port: 8081
logging:
  level:
    org:
      springframework:
        security: DEBUG
cnabparser:
  filestorage:
    location: "./"
  topics:
    cnabprocessing-topic: T_CNAB_FILE

---
spring:
  config:
    activate:
      on-profile:
        - prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_USER_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
