spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cnabparser
    username: api
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile:
        - prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_USER_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
